default:
  theme_advanced_toolbar_location: top
  theme_advanced_toolbar_align: left
  theme_advanced_statusbar_location: bottom
  theme_advanced_buttons3_add:
    - tablecontrols
    - fullscreen
  plugins:
    - table
    - fullscreen

alternate:
  theme: 'advanced'
  mode: 'textareas'
  theme_advanced_buttons1:
    - mylistbox
    - mysplitbutton
    - bold
    - italic
    - underline
    - strikethrough
    - separator
    - justifyleft
    - justifycenter
    - justifyright
    - justifyfull
    - separator
    - bullist
    - numlist
    - separator
    - undo
    - redo
    - separator
    - link
    - unlink
    - anchor
  theme_advanced_buttons2:
    - cut
    - copy
    - paste
    - separator
    - outdent
    - indent
    - blockquote
    - separator
    - image
    - media
    - separator
    - forecolor
    - backcolor
    - separator
    - preview
    - fullscreen
  theme_advanced_buttons3: ''
  plugins:
    - fullscreen
    - preview
    - media
    - inlinepopups
    - advimage
    - advlink
    - autolink
    - autoresize
    - paste